### ISSUE TITLE
Random entity textures

### ISSUE THREAD

**Issue by Madis0** [dorianpb/cem#10]
I am aware of [at least one mod](https://www.curseforge.com/minecraft/mc-mods/varied-mob-textures) that can do that, but since this mod handles entity models as well, maybe you'll also consider adding that feature.

**Comment by NatoBoram** [comment]
Hi @Madis0, there's a new mod that adds OptiFine's random entity textures.

* https://github.com/btrab1/EmissiveMod
* https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric
