### ISSUE TITLE
0.7.2 not marked correctly on modrinth

### ISSUE THREAD

**Issue by Aces-and-Jacks** [dorianpb/cem#118]
As said in tittle 0.7.2 should be 1.19.3 only up instead of 1.19--1.19.3

**Comment by DearFox** [comment]
![image](https://user-images.githubusercontent.com/59219907/218446506-09046ba1-9439-444a-aa44-d1fa845ceede.png)
I also noticed that not all versions are compatible with 1.19.2
Only the dedicated version is compatible with 1.19.2, this is really misleading 
I think you need to specify compatible versions and names in more detail

**Comment by stantios** [comment]
> ![image](https://user-images.githubusercontent.com/59219907/218446506-09046ba1-9439-444a-aa44-d1fa845ceede.png) 
I also noticed that not all versions are compatible with 1.19.2 Only the dedicated version is compatible with 1.19.2, this is really misleading I think you need to specify compatible versions and names in more detail

This kinda links in with what I'm going to say but, could you mark 0.7.1 compatible with 1.19.1 and 1.19.2 as they are both compatible with this version? I have just tested them and they both work perfectly for each version

**Comment by DearFox** [comment]
> > ![image](https://user-images.githubusercontent.com/59219907/218446506-09046ba1-9439-444a-aa44-d1fa845ceede.png)
> > I also noticed that not all versions are compatible with 1.19.2 Only the dedicated version is compatible with 1.19.2, this is really misleading I think you need to specify compatible versions and names in more detail
> 
> This kinda links in with what I'm going to say but, could you mark 0.7.1 compatible with 1.19.1 and 1.19.2 as they are both compatible with this version? I have just tested them and they both work perfectly for each version

for me only one of them works with 1.19.2

**Comment by stantios** [comment]
> > > ![image](https://user-images.githubusercontent.com/59219907/218446506-09046ba1-9439-444a-aa44-d1fa845ceede.png)
> > > I also noticed that not all versions are compatible with 1.19.2 Only the dedicated version is compatible with 1.19.2, this is really misleading I think you need to specify compatible versions and names in more detail
> > 
> > 
> > This kinda links in with what I'm going to say but, could you mark 0.7.1 compatible with 1.19.1 and 1.19.2 as they are both compatible with this version? I have just tested them and they both work perfectly for each version
> 
> for me only one of them works with 1.19.2

By that, I mean 0.7.1 is compatible with 1.19.2 and 1.19.1. 0.7.1 has a port to 1.19.3 which cannot be used on 1.19.2 and 1.19.1, but yeah maybe in the version title they could specify whether the version is for 1.19.3 or 1.19.2 rather than only saying the version number.

**Comment by stantios** [comment]
This issue is now fixed and the 0.7.2 version is now unmarked for 1.19.2 on Modrinth so this issue can now be closed.
