### ISSUE TITLE
Fish CEM support

### ISSUE THREAD

**Issue by TrillionDeTurtle** [dorianpb/cem#12]
I am using the latest version of CEM

No support for custom salmom

you would be able to use the optifine format to make different salmon texures and models

I dont have any screenshots but the readme.md doesnt list fish as working models

 - OS: Windows 10 home
 - Java Version: 16
 - Minecraft Version: 1.17.1

**Additional context**

**Comment by dorianpb** [comment]
If the readme doesn't list fish as supported, then they aren't supported. I'll work on it though

**Comment by TrillionDeTurtle** [comment]
cool, i made a resourcepack that doubles the scale of the salmon model, to make them look like bedrock big salmon and im hoping for support on cem

**Comment by TrillionDeTurtle** [comment]
any update?

**Comment by dorianpb** [comment]
I currently am really busy right now but I should be able to get it done by the end of this week

**Comment by dorianpb** [comment]
Sorry for the wait

**Comment by dorianpb** [comment]
Commit bcaa56fac7b7d23b43fda329c59e4e902b373997 adds support for salmon!
They'll be in the next release
