### ISSUE TITLE
[BUG] Crash on 1.19.2

### ISSUE THREAD

**Issue by TechPro424** [dorianpb/cem#122]
**Version**
 I am using the latest version of CEM (v0.7.2)

**Describe the bug**
Crashes when launching the game
Game log: https://mclo.gs/bGWNz9H
Mods: https://moddermore.net/list/9c82cc90d0

**Expected behavior**
I expected the game to launch

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Java Version: 17
 - Minecraft Version: 1.19.2

**Comment by Felina-Lain** [comment]
Pretty sure they made an error when giving the compatible game version, because the dependencies are all for 1.19.3

**Comment by TechPro424** [comment]
Seems to have been fixed in 0.7.3
