### ISSUE TITLE
Upload to modrinth

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [dorianpb/cem#13]
Could you also upload the release versions to modrinth (by release versions I mean the ones you upload to curseforge)

**Comment by dorianpb** [comment]
Why?

**Comment by DragonEggBedrockBreaking** [comment]
Modrinth is a more user friendly platform than curseforge, it has a better ui, better filters, dark theme, doesn’t make you wait 5 seconds when you try to download a mod, is open source…

**Comment by dorianpb** [comment]
I'll consider it depending on how much extra work it is

**Comment by DragonEggBedrockBreaking** [comment]
this is still relevant (commenting to remove stale marking)

**Comment by dorianpb** [comment]
Yeah this might be a while

**Comment by dorianpb** [comment]
just uploaded to modrinth, now under review

**Comment by DragonEggBedrockBreaking** [comment]
Nice

**Comment by dorianpb** [comment]
https://modrinth.com/mod/cem
