### ISSUE TITLE
entity texture not showing up

### ISSUE THREAD

**Issue by Daily212** [dorianpb/cem#16]
idk why but all cem entity texture not showing,I tried the creeper skelly texture pack and it semms not working
https://imgur.com/FCWLF2O
https://imgur.com/1dcYRsE

**Comment by dorianpb** [comment]
reopen the issue using the bug template

**Comment by Daily212** [comment]
when i checked on optifine cem the entity model also not showing up,maybe 1.17.1 optifine cem has diffrent code,my bad

Sorry!
