### ISSUE TITLE
[Question] Are random mobtextures also possible/planned?

### ISSUE THREAD

**Issue by Anfauglir-Jakob** [dorianpb/cem#20]
Optifine also features the possibility to assign multiple textures to entities, depending on a variety of different cases.
Is this also a feature of this mod or maybe planned for the future?

https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/random_entities.properties

**Comment by NatoBoram** [comment]
Hi @Anfauglir-Jakob, there's a new mod that adds OptiFine's random entity textures.

* https://github.com/btrab1/EmissiveMod
* https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric

**Comment by Anfauglir-Jakob** [comment]
Thank you very much! ^^
I’ll have a look at it as soon as I can.
