### ISSUE TITLE
Add support for Tridents

### ISSUE THREAD

**Issue by CrusherD2** [dorianpb/cem#23]
**Version**

- [ ] I am using the latest version of CEM

**Describe the bug**

I am running a texturepack called "The Mjolnir hammer" https://www.planetminecraft.com/texture-pack/mj-lnir-trident-5257081/ that adds new textures to the game, most of it is CIT so I use the mod CIT Resewn but the trident in particular has a 3d model as well as some textures, the textures load fine but the 3d model doest, same example can apply with this texture pack https://www.planetminecraft.com/texture-pack/copper-trident-optifine/ 

**Expected behavior**

The trident is supposed to be in 3d but is in 2d instead.

**Screenshots**

Fabric with CEM and CIT Resewn installed
![image](https://user-images.githubusercontent.com/89212751/138574739-42cca53a-be66-4ba9-b375-fa6718312355.png)
Optifine
![image](https://user-images.githubusercontent.com/89212751/138574770-9edbb937-b08e-4529-a1e8-daa7c3be4c76.png)

**Desktop (please complete the following information):**

 - OS: Windows 11 latest
 - Java Version: jdk 16
 - Minecraft Version: 1.17.1 for optifine and for fabric

**Comment by paatrickjohns** [comment]
I would love this feature too! Do you have any sort of timeline as to when this might be done? Cheers

**Comment by dorianpb** [comment]
Added in 3e81638a76d3bc072e08dad646799a4a1a06a1ef
