### ISSUE TITLE
[BUG] Entity animations are reversed.

### ISSUE THREAD

**Issue by NTSCMaster** [dorianpb/cem#26]
It seems that every animation part applied to entities use the wrong part of the texture. I'm using the [Misa's Realistic](https://www.curseforge.com/minecraft/texture-packs/misas-realistic) pack, and all of the animated eyes are blinking in reverse.

**Comment by NTSCMaster** [comment]
Wait this was the wrong mod. Sorry for any confusion.

**Comment by dorianpb** [comment]
oh that's fortunate for me
