### ISSUE TITLE
Suggestion: emmesive textures

### ISSUE THREAD

**Issue by mineland-0066** [dorianpb/cem#3]
aye, dunno if anyone else will see this apart from the dev, but support for optifines emmesive textures format (or a custom one at least) would be cool to have for mobs without optifine.
leaving this as a suggestion tho as i like the way the project is going on

**Comment by dorianpb** [comment]
I don't think emissive textures would be covered by this mod, but probably by one of the rendering ones... Maybe ask the devs of iris or canvas?
