### ISSUE TITLE
Vanilla tweaks smash endermen are broken

### ISSUE THREAD

**Issue by hellosway** [dorianpb/cem#4]
![2021-06-22_09 55 51](https://user-images.githubusercontent.com/83884198/122968497-74731980-d340-11eb-96a4-d9b0f0fbb199.png)
The smash endermen from vanillatweaks are transparent in the middle, and dont turn direstions, and have no face. Happens with and without canvas.

[latest.log](https://github.com/dorianpb/cem/files/6696121/latest.log)

**Comment by dorianpb** [comment]
The commit de08de71f5a1fad8db64c4042cd4f8bc276af530 fixes the animation issue. The texture issue appears in blockbench as well; could you please show me what the exact same thing looks like in optifine?

**Comment by SkyNinja** [comment]
Since the user who made this issue never responded, I took a picture of this model in Optifine myself.
![2021-12-05 (1)](https://user-images.githubusercontent.com/4765557/144791354-b28a823f-8550-46dc-9dca-19b931f12bc6.png)
