### ISSUE TITLE
Lang files question

### ISSUE THREAD

**Issue by Julienraptor01** [dorianpb/cem#45]
Why do you do this
```
  "config.cem.use_optifine_folder.tooltip.0": "This will load CEM models from  ",
  "config.cem.use_optifine_folder.tooltip.1": "assets/minecraft/optifine/cem,",
  "config.cem.use_optifine_folder.tooltip.2": "which is exactly what optifine does.",
  "config.cem.use_optifine_folder.tooltip.3": "Reload resources (F3 + T) for",
  "config.cem.use_optifine_folder.tooltip.4": "this to take effect!",
```
instead of just using \n to create a new line ?
```
  "config.cem.use_optifine_folder.tooltip": "This will load CEM models from\nassets/minecraft/optifine/cem\nwhich is exactly what optifine does.\nReload resources (F3 + T) for\nthis to take effect!",
```
(modified example)

**Comment by Julienraptor01** [comment]
i'm asking this because i want to translate this mod.

**Comment by dorianpb** [comment]
Minecraft doesn't support '\n'

**Comment by Julienraptor01** [comment]
Why does it work there ? What is different ?
https://github.com/PepperCode1/Item-Model-Fix/blob/1.18/dev/src/main/resources/assets/itemmodelfix/lang/en_us.json

**Comment by dorianpb** [comment]
wait what
didn't know that was possible
just do it either way you want then

**Comment by Julienraptor01** [comment]
No problem. We can't always know everything. Do i modify other languages too ?

**Comment by dorianpb** [comment]
honestly I'm not sure the other way is better (the fabric wiki recommends my way) so let me handle that

**Comment by Julienraptor01** [comment]
OK I'm going to wait until you know what is the best thing to do

**Comment by dorianpb** [comment]
if you want me to choose which way, do it my way, but honestly I don't really care much
