### ISSUE TITLE
[BUG] issue

### ISSUE THREAD

**Issue by StormyFabric** [dorianpb/cem#48]
**Version**

- [0.7.0 Fabric] I am using the latest version of CEM

**Describe the bug**

Crash to launcher upon installing FirstPersonModel (Found here https://www.curseforge.com/minecraft/mc-mods/first-person-model)

**Expected behavior**

Game to launch without issue.

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Ram: 16GB (Using 10GB through JVM Arguments)
 - Processor: AMD Ryzen 5 2600X Hex-Core
 - Graphics Processing Unit: AMD RX 5700 XT
 - Java Version: 17
 - Minecraft Version: 1.18.1
 - Fabric: 0.13.3

**Additional context**

- Crash Log: https://paste.ee/p/Cuk7D

**Comment by dorianpb** [comment]
the paste link says "paste not found"
could you please reupload a log showing the crash?
