### ISSUE TITLE
Request for Another Toggleable Config Option

### ISSUE THREAD

**Issue by WeegeeTheDoggo** [dorianpb/cem#52]
I've noticed that when I use "assets/minecraft/optifine/cem" in the config, it pulls its textures from assets/minecraft/textures/entity. For many resource packs, this is perfectly fine and usable, but the reason I noticed this, is because my resource pack uses its CEM textures directly from assets/minecraft/optifine/mob. I do this so that entity textures do not try displaying over an incorrect model when you don't use optifine with my pack, or are using another resource pack above mine. I would Greatly appreciate it if you'd add an option in the configs for it to pull textures from there instead of the vanilla folders.

**Comment by dorianpb** [comment]
.jem files have an option to specify texture location.
do you not need to do that on optifine?

**Comment by WeegeeTheDoggo** [comment]
nope, it just uses textures from optifine/mob if you tell it to do so in a .properties file within the optifine/mob folder(s), making use of random entities. I suppose I could point the .jem to a single texture, but if an entity has multiple textures via random entities, it won't be possible (unless ya know a better way) to use em all unless a way is added in this mod for us to either specify a path in the config itself, or have an option specific to the optifine/mob path
