### ISSUE TITLE
[BUG] Failed to load texture (Terrr's Animals Redone compat.)

### ISSUE THREAD

**Issue by Felix14-v2** [dorianpb/cem#58]
**Version**
Latest (0.7.1)

**Description**
Currently it is impossible to get entity textures using Terrr's Animals Redone resoursepack

<details>
 <summary>
 
**Screenshots**

</summary>

![image](https://user-images.githubusercontent.com/75726196/165074220-63854b2d-6837-499e-9de1-01dc003f0900.png)
![image](https://user-images.githubusercontent.com/75726196/165074232-cc33b369-54c2-4ab2-9506-86dcd9473f69.png)
OF:
![image](https://user-images.githubusercontent.com/75726196/165075598-3539e359-55a5-44d6-bfa8-6f0511918c3b.png)
![image](https://user-images.githubusercontent.com/75726196/165075611-2f70edef-6003-4fd5-996b-4cf86a1fb5b5.png)

</details>

**Technical Info**

 - OS: Windows 10
 - Java Version: Java 17.0.1 Adoptium
 - Minecraft Version: 1.18.2
 - [latest.log](https://github.com/dorianpb/cem/files/8553825/latest.log)

**Additional context**
[terrr-s-animals-redone.zip](https://github.com/dorianpb/cem/files/8553763/terrr-s-animals-redone.zip)

**Comment by 70uya** [comment]
when textures are specified in the .JEM file, the program looks for the texture in the OPTIFINE folder instead of the TEXTURES folder. deleting the specification will produce textures. COW and CHICKEN models are broken, possible ATTACH issue.

**Comment by joao-b-rosario** [comment]
> when TEXTURE PATHS are specified in the .JEM file, the program looks for the texture in the OPTIFINE folder (minecraft/optifine/textures/etc) instead of the TEXTURES folder (minecraft/textures/etc). deleting the specification will produce textures.

I've deleted the specification and I still can't get the textures.
