### ISSUE TITLE
[BUG] Invisible mobs with Fresh Animations

### ISSUE THREAD

**Issue by Robinerra** [dorianpb/cem#60]
**Version**

- [X] I am using the latest version of CEM

**Describe the bug**

Mobs are invisible when using the Fresh Animations texture pack.

**Expected behavior**

Mobs should be visible.

**Screenshots**
It's impossible to take screenshots since they cannot be photographed due to invisibility but here's my best attempt

[CEM](https://imgur.com/a/916gxkn)
[Optifine](https://imgur.com/a/dPX7k10)

**Desktop (please complete the following information):**

 - OS: Kubuntu 21.20 x86 64
 - Java Version: Adoptium 17.0.1
 - Minecraft Version: Fabric 1.18.2

**Additional context**

**Mod list:**
Fabric API
Mod menu
Light Overlay
Cloth Config
Architectury
Not enough animations
Effective
Visuality
Eating animation
Appleskin
Zaeros minimap
Iris
Sodium
Logical zoom
Lithium
Phosphor
CEM

**Shaders:**
BSL

**Resource packs:**

ABBPBR
Bare bones
Bare bones + Fresh animations
Fresh animations

**Graphics card:** GTX 1070 8GB
**RAM:** 32gb DDR4 3200MHz
**CPU:** i5-7600k

**Comment by Robinerra** [comment]
The closest I can get to a functioning version is using the Alt version of Fresh Animations (located on their mod page) and turning off the model fix, this fixes the invisibility and restores textures, but around half of mobs have issues with the animations like in #41

**Comment by Robinerra** [comment]
After some more testing it seems like the issue with most of the mobs is the Z axis of their body and head is rotated 90 degrees. I drew this to explain:
![image](https://i.imgur.com/bSAlTjj.png)

**Comment by glecknor** [comment]
where did you find the download to the alternative version? i can't seem to find it on both the planet minecraft page & the curseforge page.

**Comment by Radplay** [comment]
Still an issue, begone stale bot!

**Comment by BookWyrm114** [comment]
Can confirm this issue:
![2022-06-06_19 33 04](https://user-images.githubusercontent.com/79489385/172266295-6e59a606-be0d-4682-8e03-a74176d58774.png), hopefully it gets fixed soon, I've only experienced this issue with fresh animations, packs like [Improved Hostiles](https://www.curseforge.com/minecraft/texture-packs/improved-hostiles) seem to work fine with CEM

**Comment by Radplay** [comment]
Nope, the issue is still present

**Comment by dorianpb** [comment]
it could be because those packs aren't supposed to work with the model fix

**Comment by spAnser** [comment]
I did some digging into the files and have some observations on what seems to be happening.

This functions slightly differently than Optifine in that when a Jpm file is noted like so:
```json
{
  "part": "body",
  "id": "head_part",
  "model": "creeper_head.jpm",
  "attach": "true"
}
```

But this file doesn't exist Optifine skips over it but CEM can end up putting a null value into the models HashMap.
At least in the instance of FreshAnimations Replacing `this.models.put(newmodel.getPart(), newmodel);` with `this.models.putIfAbsent(newmodel.getPart(), newmodel);`.

Another options could be to not put the newmodel in in the event there is no model data.

https://github.com/dorianpb/cem/blob/main/src/main/java/net/dorianpb/cem/internal/file/JemFile.java#L51

As stated above you do not want the model creation fix enabled.

This fixes most models. But there is still a few like the Sheep and Pig that are orientated wrong.

The zombie in 1.6.x also is missing it's body but that seems to be because Optifine will use parts from the default model when it is missing from the jem file.

**Comment by TheFantasticLoki** [comment]
Not stale. I also experience this same issue and I am looking for a fix.
@spAnser did you happen to fix most of the pack and if so can you send a link to the modified version so I may enjoy this pack?

**Comment by TheFantasticLoki** [comment]
Took a hot minute but I tested all of the spawn eggs with the alt fresh animations pack and model fix off and these are the bugged mobs that I can find in the pack so far:
Fresh Animations Broken Mobs with CEM no Model Creation Fix:
Alley (missing body)
cats and ocelot (no head after spawning a baby)
creeper (mostly working but sometimes spawns with skeleton bodyparts)
Drowned (Missing Head)
Magma Cube (adding here cause not sure if broken or intended but floats up and down above the ground while idle and not moving.)
Phantom (model not aligned with hitbox, Model appears 1 block under hitbox)
pig (body rotated 90 degrees. Welcome back OG creeper)
piglin(random dancing and missing head inside nether)
Sheep (Same issue as Pigs, rotated body)
Edits:
Wolf (body broken spazing out)

**Comment by SoulxluoS** [comment]
Hi, install this forks for CEM and FA.
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/releases
https://github.com/YoungSoulluoS/cem/releases

> **Version**
> 
> * [x]  I am using the latest version of CEM
> 
> **Describe the bug**
> 
> Mobs are invisible when using the Fresh Animations texture pack.
> 
> **Expected behavior**
> 
> Mobs should be visible.
> 
> **Screenshots** It's impossible to take screenshots since they cannot be photographed due to invisibility but here's my best attempt
> 
> [CEM](https://imgur.com/a/916gxkn) [Optifine](https://imgur.com/a/dPX7k10)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Kubuntu 21.20 x86 64
> * Java Version: Adoptium 17.0.1
> * Minecraft Version: Fabric 1.18.2
> 
> **Additional context**
> 
> **Mod list:** Fabric API Mod menu Light Overlay Cloth Config Architectury Not enough animations Effective Visuality Eating animation Appleskin Zaeros minimap Iris Sodium Logical zoom Lithium Phosphor CEM
> 
> **Shaders:** BSL
> 
> **Resource packs:**
> 
> ABBPBR Bare bones Bare bones + Fresh animations Fresh animations
> 
> **Graphics card:** GTX 1070 8GB **RAM:** 32gb DDR4 3200MHz **CPU:** i5-7600k

**Comment by ascenstohe4vn** [comment]
why are my mobs invisible
