### ISSUE TITLE
[BUG] Enderwoman resource pack model displayed incorrectly

### ISSUE THREAD

**Issue by Hlebuw3k** [dorianpb/cem#63]
**Version**

- [v0.7.1] I am using the latest version of CEM

**Describe the bug**

The Enderwoman model is displayed like there is only 1 arm and leg origin

**Expected behavior**

It should be displayed correctly like with optifine

**Screenshots**

How its displayed with this mod
![image](https://user-images.githubusercontent.com/78320892/168906753-779cf637-8502-42bc-af80-c0ce9be3cd14.png)

How its displayed with optifine
![image](https://user-images.githubusercontent.com/78320892/168908120-e3f8aeb6-1bd2-4c45-83be-b7aca35eacaa.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Java Version: Java 17
 - Minecraft Version: 1.18.2

**Additional context**

Let a man enjoy his Enderwoman resourcepack with other fabric mods.

**Comment by dorianpb** [comment]
probably just CEM not loading things correctly? sorry but that's going to take forever to fix
