### ISSUE TITLE
[BUG] Custom models fail to load on version 0.16.1-beta-2 of Quilt modloader

### ISSUE THREAD

**Issue by PencilVoid** [dorianpb/cem#64]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

When using version 0.16.1-beta-2 or a later version of the Quilt modloader, entities are not rendered with custom models from resource packs. However, custom textures are loaded, causing a strange visual effect.

**Expected behavior**

Custom entity models are loaded with textures from the resource pack applied, looking as the resource pack creator intended.

**Screenshots**
How the models should look:
![2022-06-09_16 49 12](https://user-images.githubusercontent.com/83508866/172893493-7365873b-a029-4b1d-b5c2-04b04db8ec2f.png)

How the model ends up looking (it's not obvious from this angle, but the sheep model isn't using the vanilla texture):
![2022-06-09_17 01 25](https://user-images.githubusercontent.com/83508866/172893502-877a5c80-09f4-464d-9d77-31d6ca395795.png)

**Desktop (please complete the following information):**

 - OS: Windows 10 Pro
 - Java Version: 17
 - Minecraft Version: 1.18.2 

**Additional context**
Yes, I checked that the mod is set to check for models in the correct path.

**Comment by PencilVoid** [comment]
![2022-06-09_18 35 51](https://user-images.githubusercontent.com/83508866/172910078-9e734079-c65f-4d55-9a29-eadf51913f03.png)

**Comment by PencilVoid** [comment]
Strange... I'm testing this on version 0.16.1-beta-1, which previously worked, and now that version is having the same issue as above. I'm not sure what could be causing it.

**Comment by dorianpb** [comment]
looks like it's more of CEM not actually loading the models correctly..? does this happen on fabric too or no?

**Comment by PencilVoid** [comment]
It doesn't occur on any Fabric loader version I've tested.
