### ISSUE TITLE
[BUG] Occasional stuttering during gameplay with CEM and other mods enabled 

### ISSUE THREAD

**Issue by TalEdd** [dorianpb/cem#68]
**Version**

- [x] I am using the latest version of CEM

**Describe the bug**

Getting micro-stutters every few seconds, unless in F3 Debug Menu.

**Expected behavior**

Not supposed to stutter...

**Screenshots**

Before opening Debug, constant stutters at constant intervals:
![Before opening Debug](https://user-images.githubusercontent.com/63492921/174450352-bb3350f4-15f8-4b86-94a7-245e99c559b3.png)

After opening Debug Menu, stutters go away:
![After opening Debug Menu, stutters go away](https://user-images.githubusercontent.com/63492921/174450396-c48f0dde-e790-4e88-a247-6ad293c7e208.png)

**Desktop (please complete the following information):**

 - OS: Win 10
 - Java Version: 17
 - Minecraft Version: 1.19

**Additional context**

[Mod list](https://rentry.co/nnkbf)

**Comment by dorianpb** [comment]
does this issue persist if you remove every mod other than CEM?

**Comment by TalEdd** [comment]
With CEM and Fabric API, the constant stutter is gone, some occasional ones, maybe due to other things.

**Comment by dorianpb** [comment]
possibly. if you keep CEM (and Fabric API), and add every other mod back one or two at a time, you should be able to isolate which one is causing the problem
