### ISSUE TITLE
Add support for Allay

### ISSUE THREAD

**Issue by JoshuQuantic** [dorianpb/cem#69]
**Version**

- [ ] I am using the latest version of CEM

**Describe the bug**

**Expected behavior**

**Screenshots**

Please post screenshots of what the model looks like in this mod and in Optifine

**Desktop (please complete the following information):**

 - OS:
 - Java Version:
 - Minecraft Version: 

**Additional context**

**Comment by localfossa** [comment]
It isn't a bug it is enhancement
