### ISSUE TITLE
[BUG] issue

### ISSUE THREAD

**Issue by dbrighthd** [dorianpb/cem#7]
**Version**

 I am using the latest version of CEM

**Describe the bug**

horse legs are at the centerline

**Expected behavior**

they should appear seperated

**Screenshots**

Please post screenshots of what the model looks like in this mod and in Optifine
![2021-08-19_17 38 22](https://user-images.githubusercontent.com/68525639/130161269-5bb7e644-751c-4012-8443-9d88fa06dac7.png)
(it looks normal in optifine)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Java Version: 16JDK
 - Minecraft Version:  1.17.1

**Additional context**
https://www.curseforge.com/minecraft/texture-packs/creatures this pack (ran through the converter)

**Comment by dorianpb** [comment]
Ran through what converter?

**Comment by dbrighthd** [comment]
oops i mean to say i converted it by renaming the files

**Comment by dbrighthd** [comment]
but it might be a bug in the way that optifine handles the legs, and that optifine bug might not be present in this mod

**Comment by dorianpb** [comment]
That could definitely be it; I'll test it out when I can, as I'm currently away from my computer

**Comment by dbrighthd** [comment]
and just for more info:  the baby horse's legs seem fine 
![2021-08-19_18 04 25](https://user-images.githubusercontent.com/68525639/130162882-e733d09d-11be-48fe-948e-44d9be9daad5.png)

**Comment by dorianpb** [comment]
That makes me believe it's probably an optifine thing...
If you open the model in Blockbench, does it look normal?

**Comment by dorianpb** [comment]
This is what the jem file looks like in Blockbench (I took the liberty of using of the pack's provided horse textures):
![image](https://user-images.githubusercontent.com/29481669/130288648-ab32f013-94ee-458a-ae9b-17861faa3fe0.png)

Therefore, I'm going to mark this as "working as intended".
Just move the legs into their proper positions and it should work fine.
