### ISSUE TITLE
[BUG] Broken armor using custom entity models for humanoid models

### ISSUE THREAD

**Issue by LiLPNuTTy** [dorianpb/cem#71]
I am using the latest version of CEM

**Description**

When using a custom model for zombies, zombie villagers, all skeletons, zombified piglins, and all piglin types the armor breaks. I used an unchanged template from block bench to demonstrate this. (No other mods except for cloth config and complete config are installed) 

**Expected behavior**

Armor displays properly

**Desktop**

 - OS: Windows 10
 - Java Version: Version 8 Update 321 (build 1.8.0_321-b07)
 - Minecraft Version: 1.19 

**Screenshots**

Vanilla model with no JEM Folder 

![image](https://user-images.githubusercontent.com/73256738/175055629-a4cce68b-cab3-4d4e-978b-3599f2ac6e02.png)

Custom entity model using an unchanged template from block bench 

![image](https://user-images.githubusercontent.com/73256738/175056249-d4176b6e-de4a-4e64-a7d7-9744fde5d35e.png)

**Comment by YoungSoulluoS** [comment]
The "mirrortexture uv" setting is not correctly configured in CEM. It should flip only the texture of the arm, but also flips the armor model.

**Comment by SoulxluoS** [comment]
The "mirrortexture uv" setting is not correctly configured in CEM. It should flip only the texture of the entity model, but also flips the armor model.
