### ISSUE TITLE
[Error] Could not execute entrypoint stage 'client' due to errors, provided by 'cem'!

### ISSUE THREAD

**Issue by Kino0208** [dorianpb/cem#73]
1.18.2 Fabric
use mods：
fabric-api-0.51.1+1.18.2
optifabric-1.13.0
OptiFine_1.18.2_HD_U_H7

cloth-config-6.2.57-fabric
ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
PuzzlesLib-v3.3.5-1.18.2-Fabric

cem-0.7.1  ←[Error]
completeconfig-lib-1.4.1
entity-texture-features-3.1.4-mc1.18.x  ← [Crash Report]
modmenu-3.2.2

He doesn't seem to be compatible with Optifabric+Optifine
[latest.log](https://github.com/dorianpb/cem/files/8973949/latest.log)

**Comment by dorianpb** [comment]
optifine and/or optifabric is, in fact, incompatible and I have no intention of attempting to fix that.

optifine does what this mod does anyway so there shouldn't be a reason to install both anyway
