### ISSUE TITLE
[BUG] Resourcepack not working correctly

### ISSUE THREAD

**Issue by Terrabytes13** [dorianpb/cem#75]
- [✓] I am using the latest version of CEM

**Describe the bug**
Textures of the pack wont wrap correctly as they do when using Optifine.
![Screenshot_88](https://user-images.githubusercontent.com/108813051/177567409-baa45799-02dc-483c-acb6-76fbaa4d2c7a.png)

**Expected behavior**
Suppose to look like cute girls as per image provided.
![Screenshot_89](https://user-images.githubusercontent.com/108813051/177567470-f735b5e9-1ae2-455b-8fe7-8e7b59292025.png)

Please post screenshots of what the model looks like in this mod and in Optifine

**Desktop (please complete the following information):**

 - OS: Windows
 - Java Version: 8 Update 333 (build 1.8.0)
 - Minecraft Version: 1.18.2

**Additional context**

**Comment by Drigonis** [comment]
it looks like the model is working correctly, but it's using the vanilla texture (not going to question why on earth you're using a pack like this)
try going into the file and specifying the texture at the start (before anything else, like: texture: "<imagename>.png"
not sure about the exact formatting, it should be formatted the exact same as the following stuff, but the type should be named texture.

**Comment by Terrabytes13** [comment]
i'm not sure where or what to do with texture code as its 1. not my pack 2. ive never dealt with textures code before so know jack squat about it.
