### ISSUE TITLE
[BUG] Is this mod dead?

### ISSUE THREAD

**Issue by ardissaps** [dorianpb/cem#78]
Long time change

**Comment by LarryB123** [comment]
The last commit was 16 days ago?

**Comment by ardissaps** [comment]
> The last commit was 16 days ago?

Sorry I mean most cem resource pack is does not work  and glitched every time I tried again. I'll post screenshot when I get chance.

**Comment by dorianpb** [comment]
no it's not dead I'm working on a huge update, just on a private branch
