### ISSUE TITLE
Forge Support

### ISSUE THREAD

**Issue by Ponkhy** [dorianpb/cem#83]
Hello,

would it somehow be possible to also get this mod running with Forge ModLoader?

Thanks!

**Comment by mimi-min** [comment]
I second this! I'm sure you get this question a lot, but it's the last thing we need to be able to make the full switch over to Rubidium and say good bye to Optifine...

**Comment by dorianpb** [comment]
I'm not currently interested in supporting Forge at the moment. Sorry..
