### ISSUE TITLE
Not working with Cute Mob Models 

### ISSUE THREAD

**Issue by BrainSlugs83** [dorianpb/cem#84]
I've toggled the options every way there is, but no matter what they always appear either half way in the ground, or laying down, kicking their legs in the air.

Also some of the textures come in as black.

Everything works fine in Vanilla optifine. 🤷🏻‍♂️

**Comment by BrainSlugs83** [comment]
Bump.

**Comment by BrainSlugs83** [comment]
Also works in latest Optifabric, only broken in CEM.

It seems that Cem is not respecting the custom center position and orientation of the models the way Optifine does. -- Is this descrepancy documented?

Cem is forcing the models to all be sideways.

**Comment by NovaStorm93** [comment]
bump, all models are one block lower then normal, strange positioning issue. any way to convert the models over to CEM?

**Comment by BrainSlugs83** [comment]
I just switched back to Optifabric. -- Since, it just works. -- I feel that CEM just isn't viable.
