### ISSUE TITLE
CurseForge mark on CEM compitable with 1.19.2

### ISSUE THREAD

**Issue by Disguys** [dorianpb/cem#85]
Hello, please put a note on CurseForge that it is compatible with 1.19.2, I need it for the Modpack.

**Comment by PencilVoid** [comment]
The mod currently isn't compatible with 1.19.2. In my testing, loading the latest version of the mod with Minecraft 1.19.2 causes it to crash immediately.

**Comment by Disguys** [comment]
Maybe you have some kind of problem, because everything works well for me.

**Comment by dorianpb** [comment]
done
