### ISSUE TITLE
[BUG] issue all fresh animations mobs dont render AT ALL

### ISSUE THREAD

**Issue by MalacoX** [dorianpb/cem#90]
**Version**

- I am using the latest version of CEM

I'm using fresh animations with CEM on and no animations, just a shadow

I expected it to work and have a sheep walking around with new animations

with CEM
![image](https://user-images.githubusercontent.com/108016878/190663266-1e2473eb-14d9-45c2-8fc9-fdd81e55aa1f.png)

with optifine
![image](https://user-images.githubusercontent.com/108016878/190662895-3a759178-b414-404f-8381-9d7de72f7159.png)

 - OS: Windows 10
 - Java Version: 6
 - Minecraft Version: 1.19.2

I didn't have any mods that would change anything with the entity also this is my first time reporting a bug so uhh yeah tell me if I did something wrong

Edit: is it because I need that other mod I saw one time "animatica"

**Comment by TrueVenomized** [comment]
Animatica is for animated textures, not models, so that doesn't seem like it would be the problem.

**Comment by MalacoX** [comment]
rip

**Comment by EthanZeigler** [comment]
Attaching the log from when loading the pack. It's verbose, to say the least.

https://www.curseforge.com/minecraft/texture-packs/fresh-animations/download/3919226

https://gist.github.com/EthanZeigler/89413793c46ce1505278fbffbb317085

This is just a hunch, but checking the jem files (they're plaintext) _does_ show that these models/ids exist, however they are defined _after_ the animations in the file sequentially. Is the file parsing order sensitive to the json keys? It probably shouldn't be.

**Comment by EthanZeigler** [comment]
#11 Probably should use this thread instead

**Comment by SoulxluoS** [comment]
Hi, install this forks for CEM and FA. 
https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork/releases
https://github.com/YoungSoulluoS/cem/releases

> **Version**
> 
> * I am using the latest version of CEM
> 
> I'm using fresh animations with CEM on and no animations, just a shadow
> 
> I expected it to work and have a sheep walking around with new animations
> 
> with CEM ![image](https://user-images.githubusercontent.com/108016878/190663266-1e2473eb-14d9-45c2-8fc9-fdd81e55aa1f.png)
> 
> with optifine ![image](https://user-images.githubusercontent.com/108016878/190662895-3a759178-b414-404f-8381-9d7de72f7159.png)
> 
> * OS: Windows 10
> * Java Version: 6
> * Minecraft Version: 1.19.2
> 
> I didn't have any mods that would change anything with the entity also this is my first time reporting a bug so uhh yeah tell me if I did something wrong
> 
> Edit: is it because I need that other mod I saw one time "animatica"
